[package]
name = "gtokenchecker-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
reqwest = {version = "0.12.12", features = ["json"]}
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
