pub const DISCORD_CDN_BASE: &str = "https://cdn.discordapp.com";
pub const USER_FLAGS: &[(i128, &str)] = &[
    (1 << 0, "Staff"),
    (1 << 1, "Guild Partner"),
    (1 << 2, "HypeSquad Events Member"),
    (1 << 3, "Bug Huner Level 1"),
    (1 << 4, "SMS 2FA Enabled"),
    (1 << 5, "Dismissed Nitro promotion"),
    (1 << 6, "House Bravery Member"),
    (1 << 7, "House Brilliance Member"),
    (1 << 8, "House Balance Member"),
    (1 << 9, "Early Nitro Supporter"),
    (1 << 10, "Team Supporter"),
    (1 << 13, "Unread urgent system messages"),
    (1 << 14, "Bug Hunter Level 2"),
    (1 << 15, "Under age account"),
    (1 << 16, "Verified Bot"),
    (1 << 17, "Early Verified Bot Developer"),
    (1 << 18, "Moderator Programs Alumni"),
    (1 << 19, "Bot uses only http interactions"),
    (1 << 20, "Marked as spammer"),
    (1 << 22, "Active Developer"),
    (1 << 23, "Provisional Account"),
    (1 << 33, "Global ratelimit"), // User has their global ratelimit raised to 1,200 requests per second
    (1 << 34, "Deleted account"),
    (1 << 35, "Disabled for suspicious activity"),
    (1 << 36, "Self-deleted account"),
    (1 << 41, "User account is disabled"),
];
pub const USER_PERMISSIONS: &[(i128, &str)] = &[
    (1 << 0, "CREATE_INSTANT_INVITE"),
    (1 << 1, "KICK_MEMBERS"),
    (1 << 2, "BAN_MEMBERS"),
    (1 << 3, "ADMINISTRATOR"),
    (1 << 4, "MANAGE_CHANNELS"),
    (1 << 5, "MANAGE_GUILD"),
    (1 << 6, "ADD_REACTIONS"),
    (1 << 7, "VIEW_AUDIT_LOG"),
    (1 << 8, "PRIORITY_SPEAKER"),
    (1 << 9, "STREAM"),
    (1 << 10, "VIEW_CHANNEL"),
    (1 << 11, "SEND_MESSAGES"),
    (1 << 12, "SEND_TTS_MESSAGES"),
    (1 << 13, "MANAGE_MESSAGES"),
    (1 << 14, "EMBED_LINKS"),
    (1 << 15, "ATTACH_FILES"),
    (1 << 16, "READ_MESSAGE_HISTORY"),
    (1 << 17, "MENTION_EVERYONE"),
    (1 << 18, "USE_EXTERNAL_EMOJIS"),
    (1 << 19, "VIEW_GUILD_INSIGHTS"),
    (1 << 20, "CONNECT"),
    (1 << 21, "SPEAK"),
    (1 << 22, "MUTE_MEMBERS"),
    (1 << 23, "DEAFEN_MEMBERS"),
    (1 << 24, "MOVE_MEMBERS"),
    (1 << 25, "USE_VAD"),
    (1 << 26, "CHANGE_NICKNAME"),
    (1 << 27, "MANAGE_NICKNAMES"),
    (1 << 28, "MANAGE_ROLES"),
    (1 << 29, "MANAGE_WEBHOOKS"),
    (1 << 30, "MANAGE_EMOJIS"),
    (1 << 31, "USE_APPLICATION_COMMANDS"),
    (1 << 32, "REQUEST_TO_SPEAK"),
    (1 << 33, "MANAGE_EVENTS"),
    (1 << 34, "MANAGE_THREADS"),
    (1 << 35, "CREATE_PUBLIC_THREADS"),
    (1 << 36, "CREATE_PRIVATE_THREADS"),
    (1 << 37, "USE_EXTERNAL_STICKERS"),
    (1 << 38, "SEND_MESSAGES_IN_THREADS"),
    (1 << 39, "START_EMBEDDED_ACTIVITIES"),
    (1 << 40, "MODERATE_MEMBERS"),
    (1 << 41, "VIEW_CREATOR_MONETIZATION_ANALYTICS"),
    (1 << 42, "USE_SOUNDBOARD"),
    (1 << 43, "CREATE_EMOJIS"),
    (1 << 44, "CREATE_EVENTS"),
    (1 << 45, "USE_EXTERNAL_SOUNDS"),
    (1 << 46, "SEND_VOICE_MESSAGES"),
    (1 << 48, "SET_VOICE_CHANNEL_STATUS"),
    (1 << 49, "SEND_POLLS"),
    (1 << 50, "USE_EXTERNAL_APPS"),
];
pub const FRIEND_TYPE: &[(i32, &str)] = &[
    (1, "Friend"),
    (2, "Block"),
    (3, "Incoming friend request"),
    (4, "Outgoing friend request"),
];
