pub const DISCORD_CDN_BASE: &str = "https://cdn.discordapp.com";
pub const USER_FLAGS: &[(i128, &str)] = &[
    (1 << 0, "Staff"),
    (1 << 1, "Guild Partner"),
    (1 << 2, "HypeSquad Events Member"),
    (1 << 3, "Bug Huner Level 1"),
    (1 << 4, "SMS 2FA Enabled"),
    (1 << 5, "Dismissed Nitro promotion"),
    (1 << 6, "House Bravery Member"),
    (1 << 7, "House Brilliance Member"),
    (1 << 8, "House Balance Member"),
    (1 << 9, "Early Nitro Supporter"),
    (1 << 10, "Team Supporter"),
    (1 << 13, "Unread urgent system messages"),
    (1 << 14, "Bug Hunter Level 2"),
    (1 << 15, "Under age account"),
    (1 << 16, "Verified Bot"),
    (1 << 17, "Early Verified Bot Developer"),
    (1 << 18, "Moderator Programs Alumni"),
    (1 << 19, "Bot uses only http interactions"),
    (1 << 20, "Marked as spammer"),
    (1 << 22, "Active Developer"),
    (1 << 23, "Provisional Account"),
    (1 << 33, "Global ratelimit"), // User has their global ratelimit raised to 1,200 requests per second
    (1 << 34, "Deleted account"),
    (1 << 35, "Disabled for suspicious activity"),
    (1 << 36, "Self-deleted account"),
    (1 << 41, "User account is disabled"),
];
